apiVersion: maintenance.nightlyworker.com/v1alpha1
kind: NodeMaintenance
metadata:
  labels:
    app.kubernetes.io/name: nodemaintenance
    app.kubernetes.io/instance: nodemaintenance-sample
    app.kubernetes.io/part-of: nightly-worker
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: nightly-worker
  name: nodemaintenance-sample
spec:
  # TODO(user): Add fields here
